### ISSUE TITLE
Missing documentation and basic example

### ISSUE THREAD

**Issue by bartolsthoorn** [capoe/soapxx#2]
Hi, this code seems interesting, but there are a couple of things that are missing:

- How does this SOAP implementation compare to the original implementation in GAP? Why would one use this one compared to GAP?
- An example of the basic functionality. There is an example with gradients and potentials but that is a very specific use-case. For example: I have a list of N crystal structures, how does one create the `N x N` average or rematch kernel matrices with alchemical channels?

**Comment by capoe** [comment]
See the examples folder, in particular examples/molecular_kernel and examples/dmap_minimal.
